flowable:
  async-executor-activate: false # 关闭定时任务JOB
  database-schema-update: true   # 将databaseSchemaUpdate设置为true。当Flowable发现库与数据库表结构不一致时，会自动将数据库表结构升级至新版本。

logging:
  level:
    org:
      flowable: debug
