breeze:
  aesSecret: 1234567890123456
  security:
    ignore-urls:
      # Monitor
      - "/actuator/**"
      # Local file storage
      - "/img/**"
      # Data sources & Report generation
      - "/druid/**"
      - "/ureport/**"

# sa-token配置
sa-token:
  # token名称 (同时也是 Cookie 名称)
  token-name: satoken
  # 是否打印操作日志
  is-log: true
  # jwt 秘钥
  jwt-secret-key: saxsaxsaxsax
  # OAuth2.0 配置
  oauth2-server:
    # 是否全局开启授权码模式
    enable-authorization-code: true
    # 是否全局开启 Implicit 模式
    enable-implicit: true
    # 是否全局开启密码模式
    enable-password: true
    # 是否全局开启客户端模式
    enable-client-credentials: true
    # 定义哪些 scope 是高级权限，多个用逗号隔开
    # higher-scope: openid,userid
    # 定义哪些 scope 是低级权限，多个用逗号隔开
    # lower-scope: userinfo
