# 租户配置
breeze:
  tenant:
    tables:
      - "sys_permission"
      - "sys_platform"
      - "sys_user"
      - "sys_dept"
      - "sys_role"
      - "sys_dict"
      - "sys_dict_item"
      - "sys_post"
      - "sys_file"
      - "sys_log"
      - "sys_menu"
      - "sys_msg"
      - "sys_row_permission"
